<?php
echo '<!DOCTYPE html>';
echo '<html lang="es">';
echo '<head>';
echo '<meta charset="UTF-8">';
echo '<meta name="viewport" content="width=device-width, initial-scale=1.0, user-scalable=no">';
echo '<link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/font-awesome/6.5.1/css/all.min.css" integrity="sha512-DTOQO9RWCH3ppGqcWaEA1BIZOC6xxalwEsw9c2QQeAIftl+Vegovlnee1c9QX4TctnWMn13TZye+giMm8e2LwA==" crossorigin="anonymous" referrerpolicy="no-referrer" />';
echo '<link rel="stylesheet" href="portafolio web.css">';
echo '';
echo '<title>Xeno Portafolio web</title>';
echo '</head>';
echo '';
echo '<body>';
echo '';
echo '<section id="inicio">';
echo '<div class="contenido">';
echo '<header>';
echo '<div class="contenido-header">';
echo '<h1>|Xeno|</h1>';
echo '<nav id="nav" class="">';
echo '<ul id="links">';
echo '<li><a href="#inicio" class="seleccionado">INICIO</a></li>';
echo '<li><a href="#aboutme">ABOUT ME</a></li>';
echo '<li><a href="#portafolio">PORTAFOLIO</a></li>';
echo '<li><a href="#skills">SKILLS</a></li>';
echo '</ul>';
echo '</nav>';
echo '<!--iconos menu-->';
echo '<div id="icono-nav">';
echo '<i class="fa-solid fa-bars"></i>';
echo '</div>';
echo '<!--social media icons-->';
echo '<div class="redes">';
echo '<a href="https://www.youtube.com/@XenoconX" target="_blank"><i class="fa-brands fa-youtube"></i></a>';
echo '<a href="https://www.facebook.com/tugfa.enbizi.3" target="_blank"><i class="fa-brands fa-facebook"></i></a>';
echo '<a href="https://www.instagram.com/xeno.phbic/" target="_blank"><i class="fa-brands fa-instagram"></i></a>';
echo '<a href="https://github.com/Xenitojeje " target="_blank"><i class="fa-brands fa-github"></i></a>';
echo '</div>';
echo '</div>';
echo '</header>';
echo '<div class="presentacion">';
echo '<p class="bienvenida">Bienvenidos</p>';
echo '<h2>Soy <span>Diego Aguilera</span>, Estudiante de ingenieria en Software</h2>';
echo '<p class="descripcion">Estudio ingenieria en Software</p>';
echo '<a href="#portafolio">Ir a Portafolio</a>';
echo '</div>';
echo '</div>';
echo '</section>';
echo '<!--about me-->';
echo '<section id="aboutme">';
echo '<div class="contenedor-foto">';
echo '<img src="imagensobremi.jpg" alt="">';
echo '</div>';
echo '<div class="aboutme">';
echo '<p class="titulo-seccion">About me</p>';
echo '<h2>Hola, soy <span>Diego Aguilera</span></h2>';
echo '<h3>Estudiante de Ingenieria en Software</h3>';
echo '<p>Mi mayor logro actualmente es haber alcanzado el nivel C1 en el idioma inglés</p>';
echo '<p>Me gusta jugar videojuegos y aprender idiomas</p>';
echo '</div>';
echo '</section>';
echo '<!--portafolio-->';
echo '<section id="portafolio">';
echo '<h3 class="titulo-seccion">PORTAFOLIO</h3>';
echo '<div class="fila">';
echo '<div class="portafolio">';
echo '<span class="icono"><i class="fa-solid fa-code"></i></span>';
echo '<h4>Trabajos realizados</h4>';
echo '<hr>';
echo '<ul class="portafolio-tag">';
echo '<a href="https://github.com/Xenitojeje/Diego-Alexander-Mendoza-Aguilera.git " target="_blank">Unidad 2</a>';
echo '</ul>';
echo '</div>';
echo '</div>';
echo '';
echo '</section>';
echo '<!--Skills-->';
echo '<div class="contenedor-skills" id="skills">';
echo '<h3>SKILLS</h3>';
echo '<div class="skill">';
echo '<div class="info">';
echo '<p><span class="lista"></span>Ingles</p>';
echo '<span class="porcentaje">85%</span>';
echo '</div>';
echo '<div class="barra">';
echo '<div id="ingles" class=""></div>';
echo '</div>';
echo '</div>';
echo '';
echo '<div class="skill">';
echo '<div class="info">';
echo '<p><span class="lista"></span>Html</p>';
echo '<span class="porcentaje">25%</span>';
echo '</div>';
echo '<div class="barra">';
echo '<div id="html" class=""></div>';
echo '</div>';
echo '</div>';
echo '';
echo '<div class="skill">';
echo '<div class="info">';
echo '<p><span class="lista"></span>Css</p>';
echo '<span class="porcentaje">30%</span>';
echo '</div>';
echo '<div class="barra">';
echo '<div id="css" class=""></div>';
echo '</div>';
echo '</div>';
echo '';
echo '<div class="skill">';
echo '<div class="info">';
echo '<p><span class="lista"></span>JavaScript</p>';
echo '<span class="porcentaje">10%</span>';
echo '</div>';
echo '<div class="barra">';
echo '<div id="js" class=""></div>';
echo '</div>';
echo '</div>';
echo '';
echo '</div>';
echo '</body>';
echo '';
?>